### ISSUE TITLE
is this still maintained

### ISSUE THREAD

**Issue by Tsjippy** [merlinthemagic/MTM-Signal#3]
Will there be new versions coming?

**Comment by merlinthemagic** [comment]
Hi,

Yes there will be new versions coming. I can say that with some certainty because we are running up against the issue of how to deliver 2FA challenges in a way that ensures the identity of the source.

What is your use case? What is the feature you are looking for?

**Comment by Tsjippy** [comment]
We are currently looking into moving to vps hosting to be able to install java use signal-cli.

if we do we want to use your framework as it looks great. But only if it is maintained.

thanks
